[versions]
ezxhelper = "1.0.3"
kotlin = "1.9.0"
agp = "8.1.1"
xposed = "82"

[libraries]
ezxhelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezxhelper" }
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
